services:
  app:
    build:
      context: .
      no_cache: true
    image: bank-transaction-analyzer:local
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    env_file:
      - secrets/credentials.env
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongodb/mongodb-community-server:latest
    restart: always
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0", "--bind_ip_all", "--noauth"] # Enable replica set for transactions support
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "try { rs.status().ok } catch(e) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo:27017'}]}).ok }"]
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
